---
title: "EDA"
output: html_document
date: '2022-04-29'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## EDA 
```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
df_2<-read_csv("")
df <- read_csv("cleaned_data.csv") %>% 
  mutate_if(~is.numeric(.) && n_distinct(.) <8, as_factor) %>% 
  mutate_if(~is_character(.), as_factor)
```
```{r}
summary(df)
```

```{r}
colSums(is.na(df))
```

```{r}
sum(duplicated(df))
```
remove duplicates later.


### Visualization
```{r}
quants = c("Age", "App_day", "Sche_day", "Sche_hour", "Time_gap")
cate = c("Gender", "Neighbourhood", "Scholarship", "Hipertension", "Diabetes", "Alcoholism", "Handcap", "SMS_received", "App_month", "Sche_year", "Sche_month", "is_workday")
```

```{r}
ggplot(df, aes(x=Age, fill=No_show)) + geom_histogram(position="dodge")
ggplot(df, aes(x=App_day, fill=No_show)) + geom_histogram(position="dodge")
ggplot(df, aes(x=Sche_day, fill=No_show)) + geom_histogram(position="dodge")
ggplot(df, aes(x=Sche_hour, fill=No_show)) + geom_histogram(position="dodge")
ggplot(df, aes(x=Time_gap, fill=No_show)) + geom_histogram(position="dodge")
```

```{r}

ggplot(df, aes(x=Gender)) + geom_bar(aes(fill=No_show))
ggplot(df, aes(x=Neighbourhood)) + geom_bar(aes(fill=No_show))+ scale_x_discrete(labels = NULL, breaks = NULL) + labs(x = "")
ggplot(df, aes(x=Scholarship)) + geom_bar(aes(fill=No_show))
ggplot(df, aes(x=Hipertension)) + geom_bar(aes(fill=No_show))
ggplot(df, aes(x=Diabetes)) + geom_bar(aes(fill=No_show))
ggplot(df, aes(x=Alcoholism)) + geom_bar(aes(fill=No_show))
ggplot(df, aes(x=Handcap)) + geom_bar(aes(fill=No_show))
ggplot(df, aes(x=SMS_received)) + geom_bar(aes(fill=No_show))
ggplot(df, aes(x=App_month)) + geom_bar(aes(fill=No_show))
ggplot(df, aes(x=Sche_year)) + geom_bar(aes(fill=No_show))
ggplot(df, aes(x=Sche_month)) + geom_bar(aes(fill=No_show))
ggplot(df, aes(x=is_workday)) + geom_bar(aes(fill=No_show))



```

```{r}
<<<<<<< HEAD
install.packages("GGally")
dim(df)
=======
for (i in quants){
    plot <- ggplot(df, aes_string(df$No_show,i)) +
    geom_violin(aes(fill=No_show))+
    xlab("No_show")
    print(plot)
}
>>>>>>> 97994f392606d0d76a20198f345104100ab9a0f0
```


```{r}
library(GGally)
```

```{r}
?ggpairs
ggpairs(df[quants],cardinality_threshold=100)
```


